/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as PublicCalendarRouteImport } from './routes/public.calendar'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCalendarRoute = PublicCalendarRouteImport.update({
  id: '/public/calendar',
  path: '/public/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/slots': typeof SlotsRoute
  '/users': typeof UsersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/slots': typeof SlotsRoute
  '/users': typeof UsersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/bookings': typeof BookingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/slots': typeof SlotsRoute
  '/users': typeof UsersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/calendar'
    | '/import'
    | '/login'
    | '/reports'
    | '/slots'
    | '/users'
    | '/bookings/$id'
    | '/public/calendar'
    | '/bookings/'
    | '/api/public/hooks/daily-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/calendar'
    | '/import'
    | '/login'
    | '/reports'
    | '/slots'
    | '/users'
    | '/bookings/$id'
    | '/public/calendar'
    | '/bookings'
    | '/api/public/hooks/daily-backup'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/calendar'
    | '/import'
    | '/login'
    | '/reports'
    | '/slots'
    | '/users'
    | '/bookings/$id'
    | '/public/calendar'
    | '/bookings/'
    | '/api/public/hooks/daily-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CalendarRoute: typeof CalendarRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SlotsRoute: typeof SlotsRoute
  UsersRoute: typeof UsersRoute
  BookingsIdRoute: typeof BookingsIdRoute
  PublicCalendarRoute: typeof PublicCalendarRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/calendar': {
      id: '/public/calendar'
      path: '/public/calendar'
      fullPath: '/public/calendar'
      preLoaderRoute: typeof PublicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CalendarRoute: CalendarRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SlotsRoute: SlotsRoute,
  UsersRoute: UsersRoute,
  BookingsIdRoute: BookingsIdRoute,
  PublicCalendarRoute: PublicCalendarRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
